# Data: cpu/mem
# Filter: metadata-exchange and stats filters
# VM mode: nullvm
telemetry_mode: "v2-stats-nullvm"
conn:
    - 16
qps:
    - 10
    - 100
    - 1000
    - 10000
duration: 960
perf_record: false
run_bothsidecar: true
run_serversidecar: false
run_clientsidecar: false
run_baseline: false

jitter: true
